spring:
  datasource:
    hikari:
      username: test
      password: test
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.0.201:3306:3306/secretgarden?useUnicode=true&characterEncoding=utf-8
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true


    hibernate:
      ddl-auto: create
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true

  devtools:
    livereload:
      enabled: true


#spring.thymeleaf.check-template-location=true

#spring.datasource.url=jdbc:mysql://192.168.0.201:3306/test?useUnicode=true&characterEncoding=utf-8
#spring.datasource.url=jdbc:mysql://localhost:3306/secretgarden?useUnicode=true&characterEncoding=utf-8
#spring.datasource.username=root
#spring.datasource.password=1234
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

##mybatis
#mybatis.mapper-locations=classpath:mybatis/mapper/**/*.xml
#mybatis.config-location=classpath:mybatis/config/config.xml

#jpa-logging
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.show-sql=true

logging:
  level:
    org.hibernate.sql: debug # logger??? debug? ??


