
#jsp \uB9E4\uD551 \uC124\uC815
#spring.mvc.view.prefix=/WEB-INF/templates/
#spring.mvc.view.suffix=.html


#devtools \uC124\uC815
spring:
  devtools:
    livereload:
      enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true

  datasource:
    hikari:
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.0.201:3306:3306/secretgarden?useUnicode=true&characterEncoding=utf-8
  jpa:
    properties:
      hibernate:
        show_sql: true
        show-sql: true

#thymeleaf \uC811\uB450 \uC811\uBBF8 \uC124\uC815

#\uD0C0\uC784\uB9AC\uD504 \uCE90\uC2F1\uC744 \uC0AC\uC6A9\uD558\uC5EC \uBE0C\uB77C\uC6B0\uC800\uB97C \uC0C8\uB85C\uACE0\uCE68\uD588\uC744 \uB54C \uBC18\uC601\uD558\uAC8C \uD55C\uB2E4.

#templates \uB514\uB809\uD1A0\uB9AC\uC5D0 \uD30C\uC77C\uC774 \uC788\uB294\uC9C0 \uC5C6\uB294\uC9C0 \uCCB4\uD06C, \uC5C6\uC73C\uBA74 \uC5D0\uB7EC\uB97C \uBC1C\uC0DD\uC2DC\uD0A8\uB2E4.
#spring.thymeleaf.check-template-location=true

#spring.datasource.url=jdbc:mysql://192.168.0.201:3306/test?useUnicode=true&characterEncoding=utf-8
#spring.datasource.url=jdbc:mysql://localhost:3306/secretgarden?useUnicode=true&characterEncoding=utf-8
#spring.datasource.username=root
#spring.datasource.password=1234
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

##mybatis
#mybatis.mapper-locations=classpath:mybatis/mapper/**/*.xml
#mybatis.config-location=classpath:mybatis/config/config.xml

#jpa-logging
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.show-sql=true